version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: y9-db
    environment:
      MYSQL_DATABASE: y9
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - y9_data:/var/lib/mysql

volumes:
  y9_data: