spring.application.name=y9_gaming_site

spring.datasource.url=jdbc:mysql://136.116.107.44:3306/y9-game-db

spring.datasource.username=y9-user
spring.datasource.password=qio=gJss~v^j6Zxt

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

server.port=8081
